// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.

//! Build script for `unilang-drivers`.
//!
//! Scans `src/community/` for `*.rs` files (excluding `mod.rs`) and generates
//! two files into `$OUT_DIR`:
//!
//! - `community_mods.rs` — `pub mod <name>;` declarations
//!   (included by `src/community/mod.rs`)
//! - `community_drivers.rs` — `register_community_drivers` function and helpers
//!   (included by `src/lib.rs`)

use std::fs;
use std::path::Path;

fn main() {
    // Tell Cargo to re-run this script whenever the community directory changes.
    println!("cargo:rerun-if-changed=src/community/");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let community_dir = Path::new("src/community");

    // Collect *.rs files in src/community/ that are not mod.rs.
    let mut driver_names: Vec<String> = Vec::new();

    if community_dir.is_dir() {
        if let Ok(entries) = fs::read_dir(community_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) == Some("rs") {
                    if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                        if stem != "mod" {
                            driver_names.push(stem.to_string());
                        }
                    }
                }
            }
        }
    }

    // Sort for deterministic output.
    driver_names.sort();

    // ── Generate community_mods.rs ────────────────────────────────────────────
    // This file holds `pub mod <name>;` declarations for each discovered driver.
    // It is included from `src/community/mod.rs`.

    let mut mods_src = String::from("// Auto-generated by build.rs — do not edit\n");
    for name in &driver_names {
        mods_src.push_str(&format!("pub mod {};\n", name));
    }

    let mods_path = Path::new(&out_dir).join("community_mods.rs");
    fs::write(&mods_path, &mods_src).expect("Failed to write community_mods.rs");

    // ── Generate community_drivers.rs ─────────────────────────────────────────
    // This file holds `register_community_drivers` and is included from
    // `src/lib.rs`.

    let count = driver_names.len();
    let mut drivers_src = format!(
        "// Auto-generated by build.rs — do not edit\n\
         // Community drivers found: {count}\n\
         \n"
    );

    if count == 0 {
        // No community drivers — emit no-op stubs so the codebase always compiles.
        drivers_src.push_str(
            "/// No-op: no community drivers have been discovered.\n\
             pub fn register_community_drivers(_registry: &mut crate::DriverRegistry) {}\n\
             \n\
             /// Returns an empty slice: no community drivers are present.\n\
             pub fn community_exported_functions() -> Vec<&'static str> {\n\
             \tVec::new()\n\
             }\n",
        );
    } else {
        // Build the `register_community_drivers` body.
        let mut register_lines = String::new();
        for name in &driver_names {
            // Derive the struct name: capitalize first letter + append "Driver".
            let struct_name = capitalize_first(name) + "Driver";
            register_lines.push_str(&format!(
                "\tregistry.add(Box::new(crate::community::{}::{}::new()));\n",
                name, struct_name
            ));
        }

        drivers_src.push_str(&format!(
            "/// Register all auto-discovered community drivers into `registry`.\n\
             pub fn register_community_drivers(registry: &mut crate::DriverRegistry) {{\n\
             {register_lines}}}\n\
             \n\
             /// Returns an empty vec — community driver functions are gathered at\n\
             /// runtime via `DriverRegistry::all_function_names()` instead.\n\
             pub fn community_exported_functions() -> Vec<&'static str> {{\n\
             \tVec::new()\n\
             }}\n",
            register_lines = register_lines,
        ));
    }

    let drivers_path = Path::new(&out_dir).join("community_drivers.rs");
    fs::write(&drivers_path, &drivers_src).expect("Failed to write community_drivers.rs");
}

/// Capitalize only the first character of a string, leaving the rest as-is.
fn capitalize_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
    }
}
